### PR TITLE
RUN-5982 - Platforms Restyle pt 2 - Light Theme Reskin

### PR DESCRIPTION
**Pull request by MichaelMCoates**
Builds on top of this PR:
https://github.com/openfin/platform-api-project-seed/pull/13

Dependent on this core PR. Build this asar to run:
https://gitlab.com/openfin/core/-/merge_requests/1433

Ricardo's changes:
- Adds an openable sidebar to show off Platform functionality. 

- Restyles on top of Ricardo's changes to take in the new core restyling. 
- Shows and example of how to change the core's default dark theme to a light theme.
- Fixes small sidebar/panel show bugs from Ricardo's PR
- Changes Workspace to Snapshot. 

In the future, we can style up the Save Layout and Save Snapshot panels, but they work fine as is.

### CODE REVIEW

**Comment by MichaelMCoates** [comment]
This PR's ready to go now.

**Comment by dhamberlin** [comment]
Do we want to default to light mode?

**Comment by MichaelMCoates** [comment]
This currently does, yes. Or are you asking as a general question?

**Comment by dhamberlin** [comment]
Yeah in general. Do we want to merge this in and have the demo default to light? Or do dark by default and maybe have code commented that a user can uncomment to enable light. Something like that.

**Comment by MichaelMCoates** [comment]
Did a little bit of refactoring and added a theming toggle. The app seed will default to dark theme (I think it looks better), and there's now a simple square up top to toggle to light theme. Made some small changes to the core along with this, so you may need to rebuild your asar.

**Comment by MichaelMCoates** [comment]
Screen Shot 2020-05-15 at 7 11 29 PM

**Pull request merged**
